server:
  port: 9977
logging:
  config: classpath:logback.xml
  # 开发配置
spring:
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    minIdle: 100
    maxActive: 200
    initialSize: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 'ZTM' FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    maxOpenPreparedStatements: 20
    removeAbandoned: true
    removeAbandonedTimeout: 1800
    url: jdbc:mysql://localhost:3306/test?allowMultiQueries=true&useAffectedRows=true
    username: root
    password: root

efangtec:
  #  MQ账号
  mqUsername: admin
  #  QM密码
  mqPassword: admin
  #  MQ地址
  mqUrl: tcp://localhost:61616
  #开发环境
  imgurl: http://resulter.easy.echosite.cn/
  fsPath: d:/var/
  downloadExcelPath: d:/excel.xlsx
  sendMessageUrl: http://api.chanzor.com/send
  chanzorCount: yifangkeji1-yx
  chanzorPassword: 88510636